title: Decentralized Trust Interop Profile (DTIP)
description: A Lightweight Trust Profile for Decentralized and Interoperable Digital Collaboration
remote_theme: pages-themes/cayman@v0.2.0
search_enabled: true
plugins:
- jekyll-remote-theme